<?php

/**
 * @file
 * Ting Client module for Drupal
 *
 * This is a module and not a library due to the dependency on the NanoSOAP
 * module.
 *
 * All code are found in the lib/ directory and subdirectories. Inclusion of
 * code (classes) is done by ting_client.info.
 */
require_once('ting_client_class.inc');
define('TING_DEFAULT_CACHE_LIFETIME', 0);

function ting_client_validate_xsd($xsd, $action) {
  $schema = new xml_schema();
  $absolute_dir = dirname(__FILE__);

  $schema->get_from_file($absolute_dir . '/lib/xsdparse/' . $xsd);
  $seq = $schema->get_sequence($action);
  $arr[] = 'action';
  foreach ($seq as $element) {
    $s = $schema->get_element_attributes($element);
    $arr[] = $s['name'];
  }
  return $arr;
}

/**
 * Implements hook_permission().
 */
function ting_openformat_permission() {
  return array(
    'administer webservices settings' => array(
      'title' => t('Administer webservices settings'),
    ),
  );
}

/* Implements hook_menu */

function ting_client_menu() {
  $items['admin/config/serviceclient'] = array(
    'title' => 'Webservice client settings',
    'description' => 'Manage webservices.',
    'position' => 'right',
    'weight' => 20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/serviceclient/settings'] = array(
    'title' => 'Urls and settings',
    'description' => 'Manage webservice settings.',
    'weight' => -20,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_client_admin_webservices_settings'),
    'access arguments' => array('administer webservices settings'),
//'access arguments' => TRUE,	
    'file' => 'ting_client.admin.inc'
  );

  $items['admin/config/serviceclient/cache_settings'] = array(
    'title' => 'Cache settings',
    'description' => 'Configure cache settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_client_cache_admin_form'),
    'access arguments' => array('administer webservices settings'),
//'access arguments' => TRUE,
    // 'type' => MENU_LOCAL_ACTION,
    'file' => 'ting_client.admin.inc',
  );
  return $items;
}

/**
 * support for ting_client_class
 * set urls for request factory
 * */
function ting_client_set_request_factory($url_variables) {
  // has other modules any webservices
  $more = module_invoke_all('ting_client_webservice');
  if (!empty($more)) {
    $url_variables = array_merge($url_variables, $more);
  }
 
  // get the real url (variable_get)
  foreach($url_variables as $name=>$settings){
    $url_variables[$name]['url'] = variable_get($url_variables[$name]['url']);
  }
  return $url_variables;
}

/**
 * support for ting_client_class
 * get method for caching
 * use drupal::cache_get
 * */
function ting_client_cache_get($cache_key, $storage = NULL) {
  $cache = cache_get($cache_key, $storage);
  // handle cache timeout
  if ($cache && $cache->expire > 0 && $cache->expire > REQUEST_TIME) {
    return $cache;
  }
  return FALSE;
}

/**
 * support for ting_client_class
 * set method for caching
 * use drupal::cache_set
 * */
function ting_client_cache_set($cache_key, $data, $storage = NULL, $expire = NULL) {
  cache_set($cache_key, $data, $storage, $expire);
}

/**
 * support for ting_client_class
 * add a drupal message and write to watchdog
 * */
function ting_client_set_message($message = '', $type = 'status', $repeat = NULL, $watchdog = array()) {
  if (!empty($message)) {
    drupal_set_message($message, $type, $repeat);
  }
  if ($type == 'error') {
    watchdog('ting_client', $message, array(), WATCHDOG_ERROR, NULL);
  }
  if (!empty($watchdog)) {
    watchdog($watchdog['type'], $watchdog['message'], array(), WATCHDOG_ERROR, $watchdog['link']);
  }
}

/**
 * support for ting_client_class
 * enable/disable caching
 * */
function ting_client_enable_cache() {
  return variable_get('search_client_enable_cache', FALSE);
}

/**
 * support for ting_client_class
 * enable/disable logging
 * */
function ting_client_enable_logging() {
  return variable_get('ting_enable_logging', FALSE);
}

/**
 * support for ting_client_class
 * start/stop drupal timer
 * */
function ting_client_timer($action, $name) {
  $function = 'timer_' . $action;
  call_user_func_array($function, array($name));
}

/**
 * Implements hook_ding_install_tasks().
 */
function ting_client_ding_install_tasks() {
  module_load_include('inc', 'ting_client', 'ting_client.admin');
  return array(
    'ting_client_admin_webservices_settings' => array(
      'display_name' => st('Service settings'),
      'type' => 'form',
      'file' => drupal_get_path('module', 'ting_client') . '/ting_client.admin.inc',
    ),
  );
}
